# Copyright 2018-2021 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.6"

[buildpack]
  description = "A Cloud Native Buildpack that provides the Watchexec binary tool"
  homepage = "https://github.com/paketo-buildpacks/watchexec"
  id = "paketo-buildpacks/watchexec"
  keywords = ["watchexec", "reloadable", "processes"]
  name = "Paketo Watchexec Buildpack"
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/watchexec/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "bin/build", "bin/detect", "bin/main", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.dependencies]]
    id = "watchexec"
    name = "Watchexec - execute commands when watched files change"
    sha256 = "8c6e2d9ee7b7d1ceb54c1ae74cd5dd21429f2e4c77165f916560bcc146f85844"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://github.com/watchexec/watchexec/releases/download/cli-v1.17.1/watchexec-1.17.1-x86_64-unknown-linux-gnu.tar.xz"
    version = "1.17.1"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/watchexec/watchexec/blob/main/LICENSE"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "*"
