api = "0.6"

[buildpack]
  id = "paketo-buildpacks/watchexec"
  name = "Paketo Watchexec Buildpack"
  version = "{{.version}}"
  homepage = "https://github.com/paketo-buildpacks/watchexec"
  description = "A Cloud Native Buildpack that provides the Watchexec binary tool"
  keywords = ["watchexec", "reloadable", "processes"]

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.paketo.stacks.tiny"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[buildpack.licenses]]
type = "Apache-2.0"
uri  = "https://github.com/paketo-buildpacks/watchexec/blob/main/LICENSE"

[[metadata.dependencies]]
id      = "watchexec"
name    = "Watchexec - execute commands when watched files change"
version = "1.15.3"
uri     = "https://github.com/watchexec/watchexec/releases/download/1.15.3/watchexec-1.15.3-x86_64-unknown-linux-gnu.tar.xz"
sha256  = "32aeef60d9dfd0ea83cdb221c65a8e68e774e6c9255b7d9b7080f5ebaa2d535a"
stacks  = [ "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0-or-later"
  uri  = "https://github.com/watchexec/watchexec/blob/main/LICENSE"

[metdata]
pre-package   = "scripts/build.sh"
include-files = [
    "LICENSE",
    "NOTICE",
    "README.md",
    "bin/build",
    "bin/detect",
    "bin/main",
    "buildpack.toml",
  ]